[auth]
enabled = true
site_url = "http://localhost:3000"  # Update from 127.0.0.1 to localhost
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true  # Updated from false
verify_enabled = true  # Updated from false

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true  # Updated from false
secure_password_change = true
max_frequency = "1m0s"  # Updated from 1s
otp_length = 6
otp_expiry = 86400  # Updated from 3600

[auth.email.template]

[auth.sms]
enable_signup = false
