import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ProgressBar } from "@/components/molecules/progress-bar";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/molecules/theme-toggle";
import { GithubLink } from "@/components/molecules/github-link";
import { AuthListener } from "@/components/auth-listener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ProgressBar />
          <div className="absolute top-4 right-4 flex gap-2">
            <ThemeToggle />
            <GithubLink />
          </div>
          <div className="absolute top-4 left-4 max-w-screen-sm">
            <AuthListener />
          </div>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
